tasks:
  - init: |      
      sudo apt-get update && \
      sudo apt-get install -y mysql-server && \
      sudo service mysql start && \
      sleep 5 && \
      sudo mysql -u root "SHOW DATABASES;" && \
      sudo mysql -u root "CREATE DATABASE tallcms" && \
      sudo mysql -u root "CREATE USER 'laravel_user'@'localhost' IDENTIFIED BY 'strong_password'; GRANT ALL PRIVILEGES ON tallcms.* TO 'laravel_user'@'localhost'; FLUSH PRIVILEGES;" && \
      composer install && \
      echo "Instalando dependências do npm..."
      npm install && \
      
      echo "Copiando o arquivo .env..."
      cp .env.example .env && \
      
      echo "Executando migrações do banco de dados..."
      php artisan migrate:fresh --seed && \
      
      echo "Construindo a aplicação..."
      npm run build
