tasks:
  - name: Setup environment and PHP/Composer dependencies
    openMode: split-left
    init: |
      cp .env.example .env &&
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env &&
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env &&
      touch database/database.sqlite &&  # Cria o arquivo do banco de dados SQLite
      composer install --ignore-platform-reqs &&
      php artisan key:generate &&
      php artisan storage:link &&
      php artisan migrate:fresh --seed &&
      php artisan serve --host=0.0.0.0 --port=8000

  - name: Install Node dependencies and run Vite
    openMode: split-right
    command: |
      npm install &&
      npm audit fix &&
      npm run dev

ports:
  - port: 8000
    onOpen: ignore
    visibility: public
    name: PHP Server

  - port: 5173
    onOpen: ignore
    visibility: public
    name: Node Server for Vite

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
