tasks:
  - name: Setup environment and PHP/Composer dependencies
    openMode: split-left
    init: |
      cp .env.example .env &&
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env
      touch database/database.sqlite
      composer install --ignore-platform-reqs
      php artisan key:generate
      php artisan storage:link
      sudo apt-get update &&
      sudo apt-get install -y mysql-server &&
      sudo service mysql start && \
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS tallcms;" && \
      mysql -u root -e "GRANT ALL PRIVILEGES ON tallcms.* TO 'root'@'%' IDENTIFIED BY '';" && \
      mysql -u root -e "FLUSH PRIVILEGES;"
      php artisan migrate:fresh --seed
      php artisan serve

  - name: Install Node dependencies and run Vite
    openMode: split-right
    command: |
      npm install &&
      npm audit fix &&
      npm run build

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Node Server for Vite

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
