tasks:
  - init: |
      sudo apt-get update && \
      sudo apt-get install -y mysql-server && \
      sudo service mysql start && \
      sleep 5 && \  # wait 5 seconds...
      mysql -u root -e "SHOW DATABASES;" && \  
      mysql -u root -e "CREATE DATABASE tallcms;" && \  
      composer install && \
      npm install && \
      cp .env.example .env && \
      php artisan migrate:fresh --seed && \
      npm run build
