tasks:
  - init: |
      sudo apt-get update && \
      sudo apt-get install -y mysql-server && \
      sudo service mysql start && \
      mysql -u root -e "CREATE DATABASE tallcms;" && \
      composer install && \
      npm install && \
      cp .env.example .env && \
      php artisan migrate:fresh --seed && \
      npm run build
