tasks:
  - init: |
      set -e  # Faz com que o script falhe se qualquer comando falhar
      
      echo "Atualizando pacotes..."
      sudo apt-get update && \
      
      echo "Instalando MySQL Server..."
      sudo apt-get install -y mysql-server && \
      
      echo "Iniciando MySQL..."
      sudo service mysql start && \
      
      echo "Aguardando MySQL iniciar..."
      sleep 5 && \  # espera 5 segundos...
      
      echo "Listando bancos de dados..."
      mysql -u root -e "SHOW DATABASES;" && \
      
      echo "Criando banco de dados 'tallcms'..."
      mysql -u root -e "CREATE USER 'laravel_user'@'localhost' IDENTIFIED BY 'strong_password'; GRANT ALL PRIVILEGES ON tallcms.* TO 'laravel_user'@'localhost'; FLUSH PRIVILEGES;" && \
      
      echo "Instalando dependências do Composer..."
      composer install && \
      
      echo "Instalando dependências do npm..."
      npm install && \
      
      echo "Copiando o arquivo .env..."
      cp .env.example .env && \
      
      echo "Executando migrações do banco de dados..."
      php artisan migrate:fresh --seed && \
      
      echo "Construindo a aplicação..."
      npm run build
